// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC23rBtqKtsBKWtpCjsX5NzEFe5KROvi4',
    appId: '1:322337613727:web:4e0b248a919f75dbbcbfaa',
    messagingSenderId: '322337613727',
    projectId: 'app-recetas-11a04',
    authDomain: 'app-recetas-11a04.firebaseapp.com',
    storageBucket: 'app-recetas-11a04.firebasestorage.app',
    measurementId: 'G-XHVYWYK3XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5jQogq7rWC-1AaoHyzveXkEpE4w0d4iA',
    appId: '1:322337613727:android:f53fc0cbf3d98307bcbfaa',
    messagingSenderId: '322337613727',
    projectId: 'app-recetas-11a04',
    storageBucket: 'app-recetas-11a04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjMjXdZGLe00n4D_b9cnwT2tDtVHqi1hs',
    appId: '1:322337613727:ios:73fcae109b4de04abcbfaa',
    messagingSenderId: '322337613727',
    projectId: 'app-recetas-11a04',
    storageBucket: 'app-recetas-11a04.firebasestorage.app',
    iosBundleId: 'com.recetas.app.appRecetas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjMjXdZGLe00n4D_b9cnwT2tDtVHqi1hs',
    appId: '1:322337613727:ios:73fcae109b4de04abcbfaa',
    messagingSenderId: '322337613727',
    projectId: 'app-recetas-11a04',
    storageBucket: 'app-recetas-11a04.firebasestorage.app',
    iosBundleId: 'com.recetas.app.appRecetas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC23rBtqKtsBKWtpCjsX5NzEFe5KROvi4',
    appId: '1:322337613727:web:3f2e6139f27b7c9fbcbfaa',
    messagingSenderId: '322337613727',
    projectId: 'app-recetas-11a04',
    authDomain: 'app-recetas-11a04.firebaseapp.com',
    storageBucket: 'app-recetas-11a04.firebasestorage.app',
    measurementId: 'G-70E00131CJ',
  );
}
